version: "3.8"

services:
  postgres:
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: swift_edge_ledger_db
    ports:
      - "5432:5432"