line-length = 130
indent-width = 4
target-version = "py312"

[lint]
select = ["E4", "E7", "E9", "F", "N", "W", "I"]
ignore = ["N818"]
fixable = ["ALL"]
unfixable = ["N818"]

[format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = true
line-ending = "lf"
