"""create table mcc

Revision ID: 21b24d26585a
Revises: 2608e779f615
Create Date: 2025-06-28 13:17:44.393883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21b24d26585a'
down_revision: Union[str, Sequence[str], None] = '2608e779f615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcc',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'merchants', ['merchant_name'])
    op.create_foreign_key(None, 'merchants', 'mcc', ['mcc_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'merchants', type_='foreignkey')
    op.drop_constraint(None, 'merchants', type_='unique')
    op.drop_table('mcc')
    # ### end Alembic commands ###
