"""alter table set mcc.code as unique

Revision ID: e575b88d6533
Revises: 21b24d26585a
Create Date: 2025-06-28 13:27:41.640577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e575b88d6533'
down_revision: Union[str, Sequence[str], None] = '21b24d26585a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'mcc', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mcc', type_='unique')
    # ### end Alembic commands ###
